/**
 * Calendar months in a project's own timezone, for care reports.
 *
 * A care report covers one month as the client lives it: September in Sofia
 * starts at 21:00 UTC on 31 August, and a month that crosses a DST change is
 * an hour longer or shorter than its days suggest. Intl knows every zone's
 * rules, so local wall time is read from it and turned back into an instant by
 * correcting a UTC guess with the offset in force at the answer. No binding is
 * needed, so the pages and the check script import it directly.
 */

const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const pad = (n: number) => String(n).padStart(2, '0');

/** The hour of the 1st a scheduled report is made and sent, local time. */
export const CARE_SEND_HOUR = 9;
/** How many past months can be generated by hand, besides the current one. */
export const CARE_MANUAL_MONTHS = 12;

export interface LocalParts {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  second: number;
}

export interface CarePeriod {
  /** `YYYY-MM`. */
  key: string;
  /** "September 2026". */
  label: string;
  timezone: string;
  /** The first instant of the month, local midnight, as ISO. */
  from: string;
  /** Where it ends: the next month's first instant, or now for the month so far. */
  to: string;
  /** The month so far, not yet over. */
  partial: boolean;
}

const formatters = new Map<string, Intl.DateTimeFormat>();
function formatter(timezone: string): Intl.DateTimeFormat {
  let format = formatters.get(timezone);
  if (!format) {
    format = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hourCycle: 'h23',
    });
    formatters.set(timezone, format);
  }
  return format;
}

/** An IANA name Intl accepts, such as Europe/Sofia. Fixed offsets and abbreviations other than UTC are refused. */
export function validTimezone(value: string | null | undefined): string | null {
  const zone = (value ?? '').trim();
  if (!zone || zone.length > 64 || !/^[A-Za-z][A-Za-z0-9_+\-/]*$/.test(zone)) return null;
  try {
    formatter(zone);
    return zone;
  } catch {
    return null;
  }
}

/** Wall-clock parts of an instant in a timezone. */
export function localParts(timezone: string, date: Date): LocalParts {
  const parts = formatter(timezone).formatToParts(date);
  const get = (type: string) => Number(parts.find((p) => p.type === type)?.value ?? 0);
  return { year: get('year'), month: get('month'), day: get('day'), hour: get('hour') % 24, minute: get('minute'), second: get('second') };
}

/** How far the zone's clock is ahead of UTC at an instant, in milliseconds. */
function offsetAt(timezone: string, at: number): number {
  const p = localParts(timezone, new Date(at));
  return Date.UTC(p.year, p.month - 1, p.day, p.hour, p.minute, p.second) - (at - (((at % 1000) + 1000) % 1000));
}

/**
 * The instant a local wall time names. Across a DST change the offset at the
 * guess can differ from the one at the answer, so it is corrected once with
 * the latter; a time skipped by the change lands just after it.
 */
export function zonedTime(timezone: string, year: number, month: number, day: number, hour = 0, minute = 0): Date {
  const wall = Date.UTC(year, month - 1, day, hour, minute);
  let at = wall - offsetAt(timezone, wall);
  const corrected = wall - offsetAt(timezone, at);
  if (corrected !== at) at = corrected;
  return new Date(at);
}

const keyOf = (year: number, month: number) => `${year}-${pad(month)}`;
const shift = (year: number, month: number, by: number) => {
  const index = year * 12 + (month - 1) + by;
  return { year: Math.floor(index / 12), month: (index % 12) + 1 };
};

export function parsePeriodKey(key: string | null | undefined): { year: number; month: number } | null {
  const match = /^(\d{4})-(0[1-9]|1[0-2])$/.exec(key ?? '');
  return match ? { year: Number(match[1]), month: Number(match[2]) } : null;
}

/** "September 2026". */
export function periodLabel(key: string): string {
  const parsed = parsePeriodKey(key);
  return parsed ? `${MONTH_NAMES[parsed.month - 1]} ${parsed.year}` : key;
}

/** A whole month in a timezone. */
export function monthPeriod(timezone: string, key: string): CarePeriod {
  const parsed = parsePeriodKey(key);
  if (!parsed) throw new RangeError(`Not a month: ${key}`);
  const next = shift(parsed.year, parsed.month, 1);
  return {
    key,
    label: periodLabel(key),
    timezone,
    from: zonedTime(timezone, parsed.year, parsed.month, 1).toISOString(),
    to: zonedTime(timezone, next.year, next.month, 1).toISOString(),
    partial: false,
  };
}

/** The local month an instant falls in, `YYYY-MM`. */
export function monthOf(timezone: string, at: Date): string {
  const p = localParts(timezone, at);
  return keyOf(p.year, p.month);
}

/** The month before the one an instant falls in: what a report sent then covers. */
export function previousMonth(timezone: string, at: Date): string {
  const p = localParts(timezone, at);
  const before = shift(p.year, p.month, -1);
  return keyOf(before.year, before.month);
}

/** This month up to now, for "Generate this month so far". */
export function monthSoFar(timezone: string, now: Date): CarePeriod {
  const whole = monthPeriod(timezone, monthOf(timezone, now));
  return { ...whole, to: now.toISOString(), partial: true };
}

/**
 * The months the owner may generate by hand: this one so far, then the
 * twelve before it, newest first.
 */
export function manualPeriods(timezone: string, now: Date): string[] {
  const p = localParts(timezone, now);
  return Array.from({ length: CARE_MANUAL_MONTHS + 1 }, (_, i) => {
    const m = shift(p.year, p.month, -i);
    return keyOf(m.year, m.month);
  });
}

/** The period a manual generation covers: the month so far for the current month, the whole month otherwise. */
export function manualPeriod(timezone: string, key: string, now: Date): CarePeriod | null {
  if (!manualPeriods(timezone, now).includes(key)) return null;
  return key === monthOf(timezone, now) ? monthSoFar(timezone, now) : monthPeriod(timezone, key);
}

/**
 * The next scheduled send strictly after `after`: the 1st of a month at 09:00
 * local. Strictly after, so turning the schedule on never mails a client on
 * the spot; whoever wants a report sooner generates it.
 */
export function nextCareRun(timezone: string, after: Date): string {
  const p = localParts(timezone, after);
  let slot = zonedTime(timezone, p.year, p.month, 1, CARE_SEND_HOUR);
  if (slot.getTime() <= after.getTime()) {
    const next = shift(p.year, p.month, 1);
    slot = zonedTime(timezone, next.year, next.month, 1, CARE_SEND_HOUR);
  }
  return slot.toISOString();
}

/** "12 Sep 2026" in a timezone, like lib/dates.ts but on the client's own calendar. */
export function formatDay(value: string | null | undefined, timezone: string, fallback = '—'): string {
  const at = value ? new Date(value) : null;
  if (!at || Number.isNaN(at.getTime())) return fallback;
  const p = localParts(timezone, at);
  return `${p.day} ${MONTHS[p.month - 1]} ${p.year}`;
}

/** "12 Sep" in a timezone, for lists inside one month. */
export function formatShortDay(value: string | null | undefined, timezone: string, fallback = '—'): string {
  const at = value ? new Date(value) : null;
  if (!at || Number.isNaN(at.getTime())) return fallback;
  const p = localParts(timezone, at);
  return `${p.day} ${MONTHS[p.month - 1]}`;
}

/** "12 Sep 2026, 14:05" in a timezone. */
export function formatDayTime(value: string | null | undefined, timezone: string, fallback = '—'): string {
  const at = value ? new Date(value) : null;
  if (!at || Number.isNaN(at.getTime())) return fallback;
  const p = localParts(timezone, at);
  return `${p.day} ${MONTHS[p.month - 1]} ${p.year}, ${pad(p.hour)}:${pad(p.minute)}`;
}
