import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { build } from 'esbuild';
import { readFileSync,mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { providerToken,classifyAPNs,pushPayload } from '../src/lib/apns.ts';
const keys=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
const config={APNS_KEY_ID:'TESTKEY123',APNS_TEAM_ID:'TESTTEAM12',APNS_BUNDLE_ID:'com.easyscreencapture.ios',APNS_PRIVATE_KEY:`-----BEGIN PRIVATE KEY-----\n${Buffer.from(await crypto.subtle.exportKey('pkcs8',keys.privateKey)).toString('base64')}\n-----END PRIVATE KEY-----`};
const jwt=await providerToken(config),[header,claims,sig]=jwt.split('.');
assert.equal(JSON.parse(Buffer.from(header,'base64url')).alg,'ES256');
assert(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},keys.publicKey,Buffer.from(sig,'base64url'),new TextEncoder().encode(`${header}.${claims}`)));
assert.equal(await providerToken(config),jwt);
assert.equal(classifyAPNs(410,'Unregistered'),'invalid');assert.equal(classifyAPNs(403,'InvalidProviderToken'),'failed');assert.equal(classifyAPNs(429,'TooManyRequests'),'retry');
assert(!JSON.stringify(pushPayload('w','r')).includes('https://'));
const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY);
CREATE TABLE sessions(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id) ON DELETE CASCADE,expires_at TEXT);
CREATE TABLE watches(id TEXT PRIMARY KEY,user_id TEXT,status TEXT);
CREATE TABLE watch_runs(id TEXT PRIMARY KEY,user_id TEXT,watch_id TEXT,changed INTEGER);
INSERT INTO users VALUES('u'),('other');
INSERT INTO sessions VALUES('s','u','2099-01-01'),('other-session','other','2099-01-01');
INSERT INTO watches VALUES('w','u','active');
INSERT INTO watch_runs VALUES('r','u','w',1),('r2','u','w',1),('r3','u','w',1),('r4','u','w',1);`);
db.exec(readFileSync(new URL('../migrations/0010_mobile_push.sql',import.meta.url),'utf8'));
const bind=(sql,args=[])=>({bind:(...v)=>bind(sql,v),first:async()=>db.prepare(sql).get(...args),all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:db.prepare(sql).run(...args)})});
globalThis.__pushEnv={...config,DB:{prepare:sql=>bind(sql)}};
let calls=0,mode='ok';const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{calls++;assert.match(url,/^https:\/\/api.sandbox.push.apple.com\/3\/device\//);assert.equal(options.headers['apns-topic'],config.APNS_BUNDLE_ID);if(mode==='network')throw new Error('timeout');if(mode==='invalid')return Response.json({reason:'Unregistered'},{status:410});if(mode==='retry')return Response.json({reason:'ServiceUnavailable'},{status:503});return new Response(null,{status:200});};
const dir=mkdtempSync(join(tmpdir(),'push-check-'));
try{
 await build({entryPoints:[new URL('../src/lib/push.ts',import.meta.url).pathname],outfile:join(dir,'push.mjs'),bundle:true,platform:'node',format:'esm',plugins:[{name:'env',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.__pushEnv;',loader:'js'}));}}]});
 const push=await import(pathToFileURL(join(dir,'push.mjs')));
 const add=()=>db.prepare('INSERT OR REPLACE INTO push_devices VALUES(?,?,?,?,?,?)').run('d','u','s','a'.repeat(64),'sandbox',new Date().toISOString());
 add();await push.queuePush('r','u');assert.equal(calls,1);assert.equal(db.prepare('SELECT status FROM push_deliveries').get().status,'accepted');
 await push.queuePush('r','u');await push.drainPush();assert.equal(calls,1);
 mode='retry';await push.queuePush('r2','u');assert.equal(calls,2);db.exec("UPDATE push_deliveries SET next_attempt_at='2000-01-01' WHERE run_id='r2'");mode='ok';await Promise.all([push.drainPush(),push.drainPush()]);assert.equal(calls,3);
 mode='network';await push.queuePush('r3','u');const count=calls;await push.drainPush();assert.equal(calls,count);assert.equal(db.prepare("SELECT status FROM push_deliveries WHERE run_id='r3'").get().status,'unknown');
 mode='invalid';await push.queuePush('r4','u');assert.equal(db.prepare('SELECT count(*) AS n FROM push_devices').get().n,0);
 add();db.exec("DELETE FROM sessions WHERE id='s'");assert.equal(db.prepare('SELECT count(*) AS n FROM push_devices').get().n,0);
 const before=calls;await push.queuePush('r','u');assert.equal(calls,before);
 db.exec("INSERT INTO push_devices VALUES('foreign','u','other-session','bbbb','sandbox','2026-01-01')");await push.queuePush('r','u');assert.equal(calls,before);
 console.log('Push checks passed: ES256, caching, privacy, dedupe, concurrent claims, retries, unknown outcomes, invalid tokens, logout and ownership.');
}finally{globalThis.fetch=originalFetch;delete globalThis.__pushEnv;db.close();rmSync(dir,{recursive:true,force:true});}
